# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: candre-- <candre--@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/28 17:32:34 by candre--          #+#    #+#              #
#    Updated: 2025/12/01 16:47:02 by candre--         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

src = megaphone.cpp
GPP = c++
G_FLAGS = -Wall -Wextra -Werror -std=c++98

$(NAME): megaphone.cpp
	$(GPP) $(G_FLAGS) $(SRC) -o $(NAME)